apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "0s"
        autoscaling.knative.dev/target-burst-capacity: "0"
        autoscaling.knative.dev/window: "30s"
        autoscaling.knative.dev/min-scale: "2"
        autoscaling.knative.dev/target: "200"
    spec:
      # containerConcurrency: 50 # default is 0, means unlimited
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                # - node1
                # - node2
                - node3
      containers:
      - image: docker.io/bonavadeur/shuka:sleep
        resources:
          limits:
            cpu: 500m
            memory: 640M
        env:
        - name: TARGET
          value: "Konnichiwa >o<''"
