apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "0s"
        autoscaling.knative.dev/target-burst-capacity: "-1"
        autoscaling.knative.dev/window: "12s"
        # autoscaling.knative.dev/min-scale: "2"
        autoscaling.knative.dev/target: "10"
        # autoscaling.knative.dev/target-utilization-percentage: "100"
    spec:
      # containerConcurrency: 1
      # schedulerName: bonano-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node1
                # - node3
      containers:
      - image: docker.io/bonavadeur/helloworld-python:sleep
        resources:
            limits:
              cpu: 500m
              memory: 640M
        env:
        - name: TARGET
          value: "Konnichiwa >o<''"
# ---
# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: app
#   namespace: default
# spec:
#   template:
#     metadata:
#       annotations:
#         autoscaling.knative.dev/scale-to-zero-pod-retention-period: "0s"
#         autoscaling.knative.dev/window: "10s"
#         autoscaling.knative.dev/min-scale: "1"
#     spec:
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: kubernetes.io/hostname
#                 operator: In
#                 values:
#                 - node1
#       containers:
#       - image: docker.io/daohiep22/helloworld-python
#         env:
#         - name: TARGET
#           value: "app"
